language: go
go: 1.9.x
go_import_path: kkn.fi/viite
jobs:
    include:
        - stage: lint
          install:
              - npm install -g codeclimate-test-reporter
          script:
              - ./ci/validate-gofmt.sh
              - ./ci/lint.sh
              - ./ci/coverage.sh
          after_success:
              - codeclimate-test-reporter < coverage.txt
        - stage: test
          install: skip
          script: make test
