language: go
go_import_path: kkn.fi/viite
jobs:
    include:
        - stage: lint
          go:
              - 1.9.x
              - tip
          install:
              - npm install -g codeclimate-test-reporter
          script:
              - ./ci/validate-gofmt.sh
              - ./ci/lint.sh
              - ./ci/coverage.sh
          after_success:
              - codeclimate-test-reporter < coverage.txt
        - stage: test
          go:
              - 1.9.x
              - tip
          install: skip
          script: go test kkn.fi/viite
