language: go
go: 1.9.x
go_import_path: kkn.fi/viite
jobs:
    include:
        - stage: lint
          install:
              - npm install -g codeclimate-test-reporter
          script:
              - make lint
              - go test -coverprofile=coverage.txt -covermode=atomic kkn.fi/viite
          after_success:
              - codeclimate-test-reporter < coverage.txt
        - stage: test
          install: skip
          script: make test
